@startuml

skinparam groupInheritance 2
allowmixing

boundary Interface_Locadora
control Controlador_Locadora


class Usuario {
	- nome: String
	- email: String
	- data_nascimento: Date
	- cpf: String
	- rg: String
	- telefone: String
	- cep: String
	- endereco: String

	+ cadastrar(): int
	+ dados(): String
}

class Cliente {
	- codigo_cadastro: int
}

class Atendente {
	+ validar_documentos(int): boolean
	+ liberar_cliente(int): String
	+ recusar_locacao(int): String
}

class Time_Patio {
	+ liberar_veiculo(): String
}

Usuario <|-- Cliente
Usuario <|-- Atendente
Usuario <|-- Time_Patio

class Detran {}

class Multa {
	- id: int
	- data: Date
	- placa: String
	- local: String
	- observacoes: String	

	+ consultar_boleto(): String
}

class Infracao {
	- valor: double
	- tipo: String
	- descricao: String
	- agravante: int
}

circle iMulta

iMulta -r- Detran
Multa -( iMulta
Multa o-- Infracao : contém

class Locacao {
	- data_locacao: Date
	- data_devolucao: Date
	- pendente: boolean
	- codigo_locacao: int	
	- valor_locacao: double

	+ locar(): int
	+ atrasos(): String
}

class Veiculo {
	- nome: String
	- ano: int
	- quilometragem: int
	- cor: String
	- placa: String
	- numero_chassi: int
	- renavam: long

	+ registra(): int
	+ consulta(): String
}

class Categoria {
	- descricao: String
	- valor_locacao: double
}

class Montadora {
	- nome: String
}

Veiculo "1..*" -- Categoria : possui
Veiculo  --> Montadora : pertence
Veiculo -r- "0..*" Locacao : compõe

<> cliente_atendente_diamond

Cliente -- cliente_atendente_diamond : possui
Atendente -- cliente_atendente_diamond : possui
cliente_atendente_diamond -- "1..*" Locacao : realiza

Locacao -- "0..*" Multa : possui
Locacao -- Controlador_Locadora
Controlador_Locadora -[hidden]r- Cliente

Controlador_Locadora -l- Interface_Locadora

Multa -[hidden]l- Locacao

@enduml
